# Name for the github action
name: Release

on:
  push:
    branches:
      - master

# runs the jobs
jobs:
  build:
    # runs on ubuntu
    runs-on: ubuntu-latest
    steps:
      # checkout to github
      - uses: actions/checkout@v2

      - name: Setup GIT
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      # Run yarn install to install project packages
      - run: yarn install
      # yarn build to build the project
      - run: yarn release

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          # source_branch: '' # If blank, default: triggered branch
          destination_branch: 'develop' # If blank, default: master
          pr_title: 'Master to Develop Sync' # Title of pull request
          pr_body: 'Sync done by @${{ secrets.GITHUB_ACTOR }}' # Full markdown support, requires pr_title to be set
          # pr_template: '.github/PULL_REQUEST_TEMPLATE.md' # Path to pull request template, requires pr_title to be set, excludes pr_body
          # pr_reviewer: 'wei,worker' # Comma-separated list (no spaces)
          pr_assignee: ${{ secrets.GITHUB_ACTOR }} # Comma-separated list (no spaces)
          # pr_label: 'auto-pr' # Comma-separated list (no spaces)
          # pr_milestone: 'Milestone 1' # Milestone name
          # pr_draft: true # Creates pull request as draft
          github_token: ${{ secrets.GITHUB_TOKEN }}
